import { Movie } from './types';

export const FALLBACK_MOVIES: Movie[] = [
    {
        id: 27205,
        title: "Inception",
        overview: "Cobb, a skilled thief who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.",
        poster_path: "/oYuSndbSncS4no9pqlQzb7H90O2.jpg",
        backdrop_path: "/8ZTPMjS9vM7UvHIn6EZS9u9gn7Z.jpg",
        release_date: "2010-07-15",
        vote_average: 8.4,
        vote_count: 34000,
        genre_ids: [28, 878, 12],
        adult: false,
        popularity: 150.5,
        original_language: "en"
    },
    {
        id: 157336,
        title: "Interstellar",
        overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
        poster_path: "/gEU2QniE6E77NI6vCU67oYvUrZk.jpg",
        backdrop_path: "/p7D3H1un98Y6Bf66A59pAUn6979.jpg",
        release_date: "2014-11-05",
        vote_average: 8.4,
        vote_count: 32000,
        genre_ids: [12, 18, 878],
        adult: false,
        popularity: 140.2,
        original_language: "en"
    },
    {
        id: 155,
        title: "The Dark Knight",
        overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
        poster_path: "/qJ2tW6WMUDp9s1vmsZDbivXjrCA.jpg",
        backdrop_path: "/nMK9SzwuMBvX7C9O9ccB7p599PB.jpg",
        release_date: "2008-07-16",
        vote_average: 8.5,
        vote_count: 31000,
        genre_ids: [18, 28, 80, 53],
        adult: false,
        popularity: 130.8,
        original_language: "en"
    },
    {
        id: 13,
        title: "Forrest Gump",
        overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do.",
        poster_path: "/arw2vcBveWOVZr6pxY9L3vEW0oT.jpg",
        backdrop_path: "/3h1u9uY7MpGGT9pages_2.jpg",
        release_date: "1994-06-23",
        vote_average: 8.5,
        vote_count: 25000,
        genre_ids: [35, 18, 10749],
        adult: false,
        popularity: 110.4,
        original_language: "en"
    },
    {
        id: 680,
        title: "Pulp Fiction",
        overview: "A burger-loving hitman, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
        poster_path: "/d5iIl9h9btztUcrzUq0vEtHBscy.jpg",
        backdrop_path: "/su69mB7W4S6VPl9XnS4p6S4p6S4.jpg",
        release_date: "1994-09-10",
        vote_average: 8.5,
        vote_count: 26000,
        genre_ids: [53, 80],
        adult: false,
        popularity: 120.2,
        original_language: "en"
    },
    {
        id: 603,
        title: "The Matrix",
        overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
        poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        backdrop_path: "/lMnoYqPIsWVARvAQ8BNzKkEwQvD.jpg",
        release_date: "1999-03-30",
        vote_average: 8.2,
        vote_count: 24000,
        genre_ids: [28, 878],
        adult: false,
        popularity: 105.5,
        original_language: "en"
    },
    {
        id: 278,
        title: "The Shawshank Redemption",
        overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.",
        poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
        release_date: "1994-09-23",
        vote_average: 8.7,
        vote_count: 26000,
        genre_ids: [18, 80],
        adult: false,
        popularity: 135.0,
        original_language: "en"
    },
    {
        id: 238,
        title: "The Godfather",
        overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        release_date: "1972-03-14",
        vote_average: 8.7,
        vote_count: 19000,
        genre_ids: [18, 80],
        adult: false,
        popularity: 128.5,
        original_language: "en"
    },
    {
        id: 550,
        title: "Fight Club",
        overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
        poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        backdrop_path: "/hZkgoQYus5vegHoetptVKtyS1X2.jpg",
        release_date: "1999-10-15",
        vote_average: 8.4,
        vote_count: 27000,
        genre_ids: [18],
        adult: false,
        popularity: 98.4,
        original_language: "en"
    },
    {
        id: 120,
        title: "The Lord of the Rings: The Fellowship of the Ring",
        overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
        poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        backdrop_path: "/b30qO0T3LGEeO5B6tYJOhB6T2QK.jpg",
        release_date: "2001-12-18",
        vote_average: 8.4,
        vote_count: 24000,
        genre_ids: [12, 14, 28],
        adult: false,
        popularity: 111.0,
        original_language: "en"
    }
];
